version: '3.8'

services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-app
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
      - .env.local
    volumes:
      - .:/app
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    command: ["mongod", "--replSet", "rs0"]  # Enable replica set
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
